/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.campeonatodagalera.view;

import br.com.campeonatodagalera.login.Usuario;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author cesar
 */
public class ViewPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form ViewPrincipal
     */
    public ViewPrincipal() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator8 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        mensTelaInicial = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMListaArbitros = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        jMListaCamp = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        jMListaJog = new javax.swing.JMenuItem();
        jSeparator7 = new javax.swing.JPopupMenu.Separator();
        jMListaPartida = new javax.swing.JMenuItem();
        jSeparator9 = new javax.swing.JPopupMenu.Separator();
        jMListaTec = new javax.swing.JMenuItem();
        jSeparator10 = new javax.swing.JPopupMenu.Separator();
        jMListaTim = new javax.swing.JMenuItem();
        jSeparator11 = new javax.swing.JPopupMenu.Separator();
        jMUsuario = new javax.swing.JMenuItem();
        jMsobre = new javax.swing.JMenu();
        jmiSobre = new javax.swing.JMenuItem();
        jMsobre1 = new javax.swing.JMenu();
        jmiSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 153, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                abrirJanela(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        mensTelaInicial.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        mensTelaInicial.setText(" ");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/trofeu256.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mensTelaInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mensTelaInicial)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 129, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jTextPane1);

        jMenuBar1.setBackground(new java.awt.Color(255, 102, 0));
        jMenuBar1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jMenu2.setText("Listagem");

        jMListaArbitros.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_1, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMListaArbitros.setText("Árbitros");
        jMListaArbitros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMListaArbitrosActionPerformed(evt);
            }
        });
        jMenu2.add(jMListaArbitros);
        jMenu2.add(jSeparator5);

        jMListaCamp.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_2, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMListaCamp.setText("Campeonatos");
        jMListaCamp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMListaCampActionPerformed(evt);
            }
        });
        jMenu2.add(jMListaCamp);
        jMenu2.add(jSeparator6);

        jMListaJog.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_3, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMListaJog.setText("Jogadores");
        jMListaJog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMListaJogActionPerformed(evt);
            }
        });
        jMenu2.add(jMListaJog);
        jMenu2.add(jSeparator7);

        jMListaPartida.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_4, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMListaPartida.setText("Partidas");
        jMListaPartida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMListaPartidaActionPerformed(evt);
            }
        });
        jMenu2.add(jMListaPartida);
        jMenu2.add(jSeparator9);

        jMListaTec.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_5, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMListaTec.setText("Técnicos");
        jMListaTec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMListaTecActionPerformed(evt);
            }
        });
        jMenu2.add(jMListaTec);
        jMenu2.add(jSeparator10);

        jMListaTim.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_6, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMListaTim.setText("Times");
        jMListaTim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMListaTimActionPerformed(evt);
            }
        });
        jMenu2.add(jMListaTim);
        jMenu2.add(jSeparator11);

        jMUsuario.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_7, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMUsuario.setText("Usuários");
        jMUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMUsuarioActionPerformed(evt);
            }
        });
        jMenu2.add(jMUsuario);

        jMenuBar1.add(jMenu2);

        jMsobre.setText("Sobre");

        jmiSobre.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_8, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jmiSobre.setText("Sobre");
        jmiSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiSobreActionPerformed(evt);
            }
        });
        jMsobre.add(jmiSobre);

        jMenuBar1.add(jMsobre);

        jMsobre1.setText("Sair");

        jmiSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        jmiSair.setText("Sair");
        jmiSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiSairActionPerformed(evt);
            }
        });
        jMsobre1.add(jmiSair);

        jMenuBar1.add(jMsobre1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void abrirJanela(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_abrirJanela
        // TODO add your handling code here:
        LoginJDialoj login = new LoginJDialoj(this, true);

        login.setVisible(true);

        user = login.getUser();

        mensInicial();

    }//GEN-LAST:event_abrirJanela

    private void jMListaPartidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMListaPartidaActionPerformed
        // TODO add your handling code here:
        ListaPartidaJDialog p = new ListaPartidaJDialog(this, true);
        p.setVisible(true);
    }//GEN-LAST:event_jMListaPartidaActionPerformed

    private void jMListaTimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMListaTimActionPerformed
        // TODO add your handling code here:
        ListaTimeJDialog t = new ListaTimeJDialog(this, true);
        t.setVisible(true);
    }//GEN-LAST:event_jMListaTimActionPerformed

    private void jMListaArbitrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMListaArbitrosActionPerformed
        // TODO add your handling code here:
        ListaArbitroJDialog arb = new ListaArbitroJDialog(this, true);
        arb.setVisible(true);
    }//GEN-LAST:event_jMListaArbitrosActionPerformed

    private void jMListaCampActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMListaCampActionPerformed
        // TODO add your handling code here:
        ListaCampeonatoJDialog camp = new ListaCampeonatoJDialog(this, true);
        camp.setVisible(true);
    }//GEN-LAST:event_jMListaCampActionPerformed

    private void jMListaJogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMListaJogActionPerformed
        // TODO add your handling code here:
        ListaJogadoresJDialog jog = new ListaJogadoresJDialog(this, true);
        jog.setVisible(true);
    }//GEN-LAST:event_jMListaJogActionPerformed

    private void jMListaTecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMListaTecActionPerformed
        // TODO add your handling code here:
        ListaTecnicoJDialog t = new ListaTecnicoJDialog(this, true);
        t.setVisible(true);
    }//GEN-LAST:event_jMListaTecActionPerformed

    private void jMUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMUsuarioActionPerformed
        // TODO add your handling code here:
         AcessoUsuariosJDialog login = new AcessoUsuariosJDialog(this, true);

        login.setVisible(true);

        user = login.getUser();

                     
        ListaUsuario u = new ListaUsuario(this, true);
        u.setVisible(true);
    }//GEN-LAST:event_jMUsuarioActionPerformed

    private void jmiSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiSobreActionPerformed
        // TODO add your handling code here:
        SobreJDialog s = new SobreJDialog(this, true);
        s.setVisible(true);
    }//GEN-LAST:event_jmiSobreActionPerformed

    private void jmiSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiSairActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_jmiSairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuItem jMListaArbitros;
    private javax.swing.JMenuItem jMListaCamp;
    private javax.swing.JMenuItem jMListaJog;
    private javax.swing.JMenuItem jMListaPartida;
    private javax.swing.JMenuItem jMListaTec;
    private javax.swing.JMenuItem jMListaTim;
    private javax.swing.JMenuItem jMUsuario;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMsobre;
    private javax.swing.JMenu jMsobre1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator10;
    private javax.swing.JPopupMenu.Separator jSeparator11;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JPopupMenu.Separator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JPopupMenu.Separator jSeparator9;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JMenuItem jmiSair;
    private javax.swing.JMenuItem jmiSobre;
    private javax.swing.JLabel mensTelaInicial;
    // End of variables declaration//GEN-END:variables

    private Usuario user;

    private void mensInicial() {
        mensTelaInicial.setText("Bem vindo " + user.getNome());
    }
}
